#' @title Save graph objects
#'
#' @description Export high-quality, scalable graphics for both print and
#'   online.
#'
#' @param graph Either a DiagrammeR graph object or a diagram generated by
#'   \code{render_graph()}.
#' @param filename String for filename. Defaults to \code{NULL}.
#' @param filetype One of \code{pdf}, \code{eps}, \code{pdf}, \code{svg}.
#'   Defaults to \code{pdf}.
#' @param embed Defaults to FALSE. Automatically set to TRUE by
#'   \code{qd_embed()}.
#' @param ... Pass arguments to \code{render_graph()}, e.g., width and height
#'   (pixels) for .png files.
#'
#' @describeIn qd_save
#'
#' @import rsvg
#' @import DiagrammeRsvg
#' @export qd_save

qd_save <- function(graph, filename = NULL,
                    filetype = "pdf", embed = FALSE, ...) {

  # File Format Match Table -----------------------------------------------
  fmt_opts <- c("png" = "rsvg_png",
                "eps" = "rsvg_ps",
                "pdf" = "rsvg_pdf",
                "svg" = "rsvg_svg")

  # Checks ----------------------------------------------------------------

  ## check for valid filetype
  if (!filetype %in% names(fmt_opts)) {
    stop(paste("Filetype not supported. Choose one of:",
               paste0(names(fmt_opts), collapse = ", ")))
  }

  ## check for filename
  if (is.null(filename)) {
    stop("Must specify the 'filename' option.")
  }


  # Graph Object ----------------------------------------------------------

  ## detect whether 'graph' = graph object or pre-rendered graph
  if (class(graph)[1] == "dgr_graph") {
    rendered_graph <- DiagrammeR::render_graph(graph, ...)
  } else if (class(graph)[1] == "grViz") {
    rendered_graph <- graph
  }

  # File Save -------------------------------------------------------------
  file_fmt <- match.arg(filetype, names(fmt_opts))
  raw_img <- charToRaw(export_svg(rendered_graph))

  ## generate filename/path and make visible to qd_embd()
  fname <- paste(filename, file_fmt, sep = ".")
  if (embed) assign("fname", fname, envir = parent.frame())

  ## matches and calls rsvg_pdf(), rsvg_ps(), rsvg_eps(), or rsvg_svg
  out <- do.call(fmt_opts[[file_fmt]], list(raw_img, file = fname))
  out
}


#' @title Embed diagrams in RMarkdown or Quarto documents
#' @description A wrapper around \code{qd_save()} meant for use within R code
#'   chunks in RMarkdown documents.
#'
#' @param ... Pass arguments to \code{qd_save()}.
#'
#' @importFrom knitr include_graphics
#' @export qd_embed

qd_embed <- function(...) {
  qd_save(..., embed = TRUE)
  knitr::include_graphics(fname) # fname from qdsave()
}
